### ISSUE TITLE
Postal Xframe with postal.Request-Response

### ISSUE THREAD

**Issue by swilch83** [postaljs/postal.xframe#15]
I'm trying to use postal Xframe and postal request-Response to the synchronized communication between iframes, I do not know if libraries permits 

I am using 
postal.js v 0.10.3 
postal.request-response.js v0.3.0 
postal.federation.js v0.3.0-rc1 
postal.xframe v0.3.0 

for Deferred and promised I am using jquery 

postal.configuration.promise.createDeferred = function () {
      return new $ .Deferred (); 
}; 
postal.configuration.promise.getPromise = function (dfd) 
    return dfd.promise (); 
 }; 

It seems as if there are not subcribe or fail to create the promised,

gives me this error,

DataCloneError: The object could not be cloned. in the postal.xframe.js line 97

tested on Chrome, Firefox and IE

Thanks

**Comment by swilch83** [comment]
Hello,

I'm sorry for the delay,

I tried as you said adding this configuration
"postal.fedx.transports.xframe.configure ({safeSerialize: true});"

and not by the error "DataCloneError: The object could not be cloned," but

always goes in "timeout" and then switches to "error" of "then"

I tried to update the libraries, but nothing same behavior

I used libraries

postal.js v0.12.4
postal.request-response.js v0.3.1
postal.federation.js v0.3.0-rc2
postal.xframe v0.3.2

and I used the new syntax for function reply

envelope.reply (null, {data: "d"});

I done something wrong? you can control?

Thank You

**Comment by blitboy** [comment]
Hi, I'm seeing the same issue. I always get an error relating to 'then' being undefined when using the 'safeSerialize:true' option. 
Could someone post a working solution to cross frame request-response?
