### ISSUE TITLE
signalReady is asynchronous

### ISSUE THREAD

**Issue by jbadeau** [postaljs/postal.xframe#7]
Hi,

We have an issue with sending messages from iframes because we don't know when its OK to send messages as the ping & pong are asynchronous.

I think the signalReady method should either:

accept a callback
or return a promise

both of which would resolve after the handshake is complete.

this is similar to how the openajax managed hub client 2.0 works:

http://www.openajax.org/member/wiki/OpenAjax_Hub_2.0_Specification_Managed_Hub_Containers

var hubClient= new MyOrg.OpenAjax.hub.JavaHubClient(params);
hubClient.connect(onCompleteCallback);

**Comment by ifandelse** [comment]
This is so long overdue, but I'm dusting off the cobwebs here....updated README with information on the callback arg to signalReady (ahead of some new version overhauls I hope to implement).
